WINDOW_START_WIDTH = 850
WINDOW_MIN_WIDTH = 400
WINDOW_START_HEIGHT = 800
WINDOW_MIN_HEIGHT = 250

TITLE_FONT = ("Segoe UI", 17)
GENERAL_FONT = ("Segoe UI", 10)
GENERAL_FONT_BOLD = ("Segoe UI", 10, "bold")

DISPLAY_FLOAT_DECIMALS = 3
