APP_TITLE = "FootSwitch App"

WINDOW_START_WIDTH = 850
WINDOW_MIN_WIDTH = 850
WINDOW_START_HEIGHT = 600
WINDOW_MIN_HEIGHT = 600

TITLE_FONT = ("Segoe UI", 17)
GENERAL_FONT = ("Segoe UI", 10)
GENERAL_FONT_BOLD = ("Segoe UI", 10, "bold")
