APP_TITLE = "Foot Switch GUI"

WINDOW_START_WIDTH = 850
WINDOW_MIN_WIDTH = 400
WINDOW_START_HEIGHT = 750
WINDOW_MIN_HEIGHT = 250

TITLE_FONT = ("Segoe UI", 17)
GENERAL_FONT = ("Segoe UI", 10)
GENERAL_FONT_BOLD = ("Segoe UI", 10, "bold")

DISPLAY_FLOAT_DECIMALS = 3

MEASUREMENT_DURATION_SECONDS = 60